# Generated by Django 6.1 on 2026-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
